#!/bin/bash
# *** Internal calibration 
#     (This depends of your char's skills, please tune)

# ** Dig related
# * This value determines how many CP's per dig to have. 
# * A value of two should be OK
export CYCLE_N=2

# * The following two define the dig/cp ration, but also how long your dig takes.
# * A good ratio should be about 4:1 and you should have time to complete CYCLE_N
# * If sum of the times is related to "Extraction Time Bonus" stanza among others.
export CYCLE_DIG_TIME=6
export CYCLE_CP_TIME=10

# ** Prospect related
# * How long to wait before mats appear after start of prospect.
# * This depends of your prospect "Speed" stanza. Setting this 
# * value rather high will not hurt nor make your digging slower. 
export PROSPECT_INITIAL_TIME=17

# * How long to rest after each prospect. This setting will help regain a 
# * little before each digg so that your focus will not empty out.
# * Choose this value carefully. To high value will make filling the bag 
# * slower, but to small value will lead to focus starvation leading to degraded 
# * mats and in worst case even blow-up's 
export PROSPECT_REST_TIME=1

# * Who is allowed to control you as a puppeteer from withing game 
export PUPPETEER="Aprak"
